### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hanfeicode** [Mithweth/python-ansible#1]
In [23]: pb.run()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-2d70c75006d4> in <module>()
----> 1 pb.run()

/usr/local/lib/python2.7/site-packages/python_ansible-0.0.1-py2.7.egg/pyansible/playbook.pyc in run(self)
     57             return False
     58         for p in plays:
---> 59             if not self._play(p):
     60                 success = False
     61                 break

/usr/local/lib/python2.7/site-packages/python_ansible-0.0.1-py2.7.egg/pyansible/play.pyc in _play(self, play)
     87         self.runtime_errors = None
     88         try:
---> 89             self._tqm.run(play)
     90         except (AnsibleError, AnsibleParserError) as e:
     91             self.runtime_errors = e.message

/usr/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.pyc in run(self, play)
    240         self._initialize_processes(min(contenders))
    241 
--> 242         play_context = PlayContext(new_play, self._options, self.passwords, self._connection_lockfile.fileno())
    243         for callback_plugin in self._callback_plugins:
    244             if hasattr(callback_plugin, 'set_play_context'):

/usr/local/lib/python2.7/site-packages/ansible/playbook/play_context.pyc in __init__(self, play, options, passwords, connection_lockfd)
    237         # set options before play to allow play to override them
    238         if options:
--> 239             self.set_options(options)
    240 
    241         if play:

/usr/local/lib/python2.7/site-packages/ansible/playbook/play_context.pyc in set_options(self, options)
    304         # the attribute, as it is not always added via the CLI
    305         if hasattr(options, 'tags'):
--> 306             self.only_tags.update(options.tags)
    307 
    308         if len(self.only_tags) == 0:

TypeError: 'NoneType' object is not iterable

**Comment by Mithweth** [comment]
Could we get more info ? For instance, have you used tags in your PB ? what is the ansible version ?

**Comment by Mithweth** [comment]
Problem seems to come from ansible 2.3. The issue has been corrected
